Get rid of warnings and update bitflag code
Bastacyclop/rust_box2d pull request #13
Opened 2020-05-13 13:58 UTC by InquisitivePenguin

Currently, building the code produces a ton of warnings which can easily be fixed. So I took the time to fix all the warnings and make the code a bit more idiomatic and compliant with the current version of Rust. I also updated the bitflag code to use version `1.2.1` instead of `0.9` to fix several warnings.

Note: I had to add an unstable feature to make the code work. If there's a better way to do it, let me know.

2020-05-14 07:02 UTC, Bastacyclop commented
Hi @InquisitivePenguin, thanks for this PR!
However, I would like this library to keep working with Rust stable.
I am afraid that I am not up-to-date on the latest Rust changes, but looking at the `std::mem::MaybeUninit`, it seems like you should be able to use it on stable as well as methods such as `.as_mut_ptr()`, but not methods such as `.get_mut()`.  Maybe you can avoid using the experimental methods and you will be able to remove the unstable feature?

2020-05-14 07:19 UTC, Bastacyclop requested changes

2020-05-14 07:19 UTC, Bastacyclop commented on src/collision/shapes/chain.rs
> +            if ffi::ChainShape_get_prev_vertex(self.ptr(), v.get_mut()) {
maybe you can use `&mut *v.as_mut_ptr()` for these cases to only use stable features?

2020-05-14 07:28 UTC, Bastacyclop commented
PS: when it works with stable Rust you can also bump the [library version](https://github.com/Bastacyclop/rust_box2d/blob/master/Cargo.toml#L3) to 0.4.1 :)

2020-05-14 19:41 UTC, InquisitivePenguin commented
Sorry about the late response, but it should be fixed now.

2020-05-15 07:51 UTC, Bastacyclop commented
No worries and thanks again, that was fast :+1:

2020-05-15 07:51 UTC, Bastacyclop approved these changes

2020-05-15 07:52 UTC, merged